spring:
  application:
    name: resume-job-matcher-app
  datasource:
    password: HzUjDspU14MXFBmoVFbUT12DzygokxET
    url: jdbc:postgresql://dpg-d0taocadbo4c739friag-a.oregon-postgres.render.com:5432/resumejobmatcher
    username: nicat
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  security:
    secret: ${SECURITY_SECRET}
    token:
      expirationTime: 60
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: quliyeev.n.18@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

file:
  upload-dir: cv

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: cv-files

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

logging:
  file:
    path: logs
    name: logs/resume-app.log
